# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.CellCounts <- function(x, combos) {
    .Call(`_COMPASS_CellCounts`, x, combos)
}

CellCounts_character <- function(data, combinations) {
    .Call(`_COMPASS_CellCounts_character`, data, combinations)
}

updategammak_cov <- function(n_s, n_u, gammat, I, K, SS, alphau, alphas, alpha, mk, Istar, mKstar, pp, pb1, pb2, indi, WK1, WK0) {
    .Call(`_COMPASS_updategammak_cov`, n_s, n_u, gammat, I, K, SS, alphau, alphas, alpha, mk, Istar, mKstar, pp, pb1, pb2, indi, WK1, WK0)
}

